2018-03-19 21:43:25 [twisted] CRITICAL: Unhandled error in Deferred:
2018-03-19 21:43:25 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 40, in from_settings
    mw = mwcls()
  File "C:\Users\Administrator\myiron_man\myiron_man\pipelines.py", line 58, in __init__
    self.conn = pymysql.connect('192.168.56.101','root','123456','python',charset='utf-8')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymysql\__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymysql\connections.py", line 669, in __init__
    self.encoding = charset_by_name(self.charset).encoding
AttributeError: 'NoneType' object has no attribute 'encoding'
